/**
 * @file test_sef_parsing.c
 * @brief Test SEF file parsing using a validated COS3-compliant sample
 * 
 * The embedded sample matches the structure documented in
 * COS3_SEF_TEST_FILE_GENERATION.md and generated by generate_test_sef.c.
 */

#include "test_helpers.h"
#include <stdint.h>

/* ============================================================================
 * Little-Endian Read Helpers (per COS3 Specification Section 7.1.2)
 * ============================================================================
 * 
 * COS3 requires all multi-byte integers in SEF files to be stored in
 * little-endian byte order (Section 7.1.2, line 413).
 */

static inline uint16_t read_u16_le(const uint8_t *data) {
    return (uint16_t)data[0] | ((uint16_t)data[1] << 8);
}

static inline uint32_t read_u32_le(const uint8_t *data) {
    return (uint32_t)data[0] |
           ((uint32_t)data[1] << 8) |
           ((uint32_t)data[2] << 16) |
           ((uint32_t)data[3] << 24);
}

/* ============================================================================
 * Embedded COS3-Compliant SEF Example
 * ============================================================================
 * 
 * This sample is kept inline so the parser test does not depend on file I/O.
 */

static const uint8_t cos3_sef_example[] = {
    /* File header */
    0x66, 0x65, 0x73, 0x00, 0x00, 0x00, 0x00, 0x01,

    /* First section */
    0x01, 0x1C, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x01,
    0x05, 0x11, 0x22, 0x33, 0x44, 0x77,
    0x00, 0x00, 0x00, 0x00,
    0x01,
    0x01, 0x00,
    0x01,
    0x06, 0x00,
    0x00, 0x00,
    0x00, 0x00,
    0x06, 0x00, 0x00, 0x00,

    /* Import section */
    0x02, 0x18, 0x00, 0x00, 0x00,
    0x01,
    0x01, 0x00,
    0x00, 0x00, 0x00, 0x01,
    0x0E,
    0xD1, 0x56, 0x00, 0x01, 0x48, 0x41, 0x4F, 0x53,
    0x46, 0x41, 0x50, 0x49, 0x76, 0x31,
    0x00, 0x00,

    /* Function section */
    0x03, 0x02, 0x00, 0x00, 0x00,
    0x06, 0x00,

    /* App section */
    0x04, 0x09, 0x00, 0x00, 0x00,
    0x01,
    0x05, 0xA0, 0x00, 0x00, 0x00, 0x01,
    0x00, 0x00,

    /* Global section */
    0x05, 0x0C, 0x00, 0x00, 0x00,
    0x00, 0x00,
    0x10, 0x00,
    0x20, 0x00,
    0x30, 0x00,
    0x40, 0x00,
    0x50, 0x00,

    /* Code section */
    0x09, 0x06, 0x00, 0x00, 0x00,
    0x00, 0x20, 0x01, 0x00, 0x00, 0x00
};

#define COS3_SEF_SIZE sizeof(cos3_sef_example)

/**
 * @brief Test loading an embedded COS3-compliant SEF example
 */
static int test_cos3_sef_load(void) {
    printf("\n=== Test: COS3 Specification SEF File Loading ===\n");
    
    /* Create and initialize VM with eflash */
    GCOSVM *vm = NULL;
    GCOSResult ret = test_vm_create_and_init(&vm);
    if (!vm || ret != GCOS_SUCCESS) {
        printf("✗ FAILED: Could not create and initialize VM\n");
        return 1;
    }
    printf("✓ VM created and initialized\n");
    printf("✓ VM initialized\n");
    
    /* Print SEF file info */
    printf("\nSEF File Information:\n");
    printf("  Total size: %zu bytes\n", COS3_SEF_SIZE);
    printf("  File header: ");
    for (int i = 0; i < 8; i++) {
        printf("%02X ", cos3_sef_example[i]);
    }
    printf("\n");
    
    /* Parse file header using little-endian reads (per COS3 spec) */
    uint32_t file_type = read_u32_le(&cos3_sef_example[0]);
    uint32_t file_version = read_u32_le(&cos3_sef_example[4]);
    
    printf("  File type: 0x%08X (expected 0x00736566 for 'sef\\0')\n", file_type);
    
    /* Decode version per Appendix B: [internal][revision][minor][major] */
    uint8_t ver_major = (file_version >> 24) & 0xFF;
    uint8_t ver_minor = (file_version >> 16) & 0xFF;
    uint8_t ver_revision = (file_version >> 8) & 0xFF;
    uint8_t ver_internal = file_version & 0xFF;
    
    printf("  File version: v%d.%d.%d.%d (raw=0x%08X)\n",
           ver_major, ver_minor, ver_revision, ver_internal, file_version);
    
    /* Verify magic number */
    if (file_type == 0x00736566) {
        printf("  ✓ File type is valid (matches COS3 Table 10)\n");
    } else {
        printf("  ✗ File type mismatch! Got 0x%08X, expected 0x00736566\n", file_type);
        printf("  Note: This indicates the SEF loader needs to be fixed.\n");
    }
    
    /* Attempt to load the SEF file */
    printf("\nAttempting to load SEF file...\n");
    ret = gcos_loader_load_sef(vm, cos3_sef_example, COS3_SEF_SIZE);
    
    if (ret == GCOS_OK) {
        printf("✓ SEF file loaded successfully\n");
        printf("  Modules loaded: %u\n", vm->module_count);
        printf("  Apps loaded: %u\n", vm->app_count);
        printf("  Runtime code size: %u bytes\n", vm->runtime.code_size);
        gcos_vm_destroy(vm);
        return 0;
    }

    printf("✗ FAILED: SEF file loading failed (ret=%d)\n", ret);
    gcos_vm_destroy(vm);
    return 1;
}

/**
 * @brief Test module dependency resolution by AID
 */
static int test_dependency_by_aid(void) {
    printf("\n=== Test: Module Dependency Resolution by AID ===\n");
    
    GCOSVM *vm = gcos_vm_create();
    if (!vm) {
        printf("✗ FAILED: Could not create VM\n");
        return 1;
    }
    
    GCOSResult ret = gcos_vm_init(vm);
    if (ret != GCOS_OK) {
        printf("✗ FAILED: VM initialization failed\n");
        gcos_vm_destroy(vm);
        return 1;
    }
    
    printf("\nCOS3 Specification: Module dependencies are based on AID\n");
    printf("Unlike WebAssembly which uses module name strings,\n");
    printf("GCOS/COS3 uses AID (Application Identifier) for module identification.\n");
    
    /* Create a mock imported module */
    GCOSModule *imported_module = &vm->modules[0];
    imported_module->module_id = 1;
    imported_module->module_aid.length = 14;
    memcpy(imported_module->module_aid.aid, 
           "\xD1\x56\x00\x01\x48\x41\x4F\x53\x46\x41\x50\x49\x76\x31", 14);
    imported_module->version = 0x01000000;
    imported_module->state = MODULE_VERIFIED;
    imported_module->loaded = true;
    vm->module_count = 1;
    
    printf("\nMock Imported Module:\n");
    printf("  Module ID: %u\n", imported_module->module_id);
    printf("  AID: ");
    for (int i = 0; i < imported_module->module_aid.length; i++) {
        printf("%02X", imported_module->module_aid.aid[i]);
    }
    printf("\n");
    printf("  Version: %u.%u.%u.%u\n",
           (imported_module->version >> 24) & 0xFF,
           (imported_module->version >> 16) & 0xFF,
           (imported_module->version >> 8) & 0xFF,
           imported_module->version & 0xFF);
    
    /* Simulate import dependency */
    GCOSModule *dependent_module = &vm->modules[1];
    dependent_module->module_id = 2;
    dependent_module->import_count = 1;
    dependent_module->imports[0].module_version = 0x01000000;
    memcpy(&dependent_module->imports[0].module_aid, 
           &imported_module->module_aid, sizeof(GCOSAID));
    dependent_module->imports[0].resolved = false;
    dependent_module->imports[0].resolved_module_id = 0xFF;
    
    printf("\nDependent Module Import:\n");
    printf("  Required AID: ");
    for (int i = 0; i < dependent_module->imports[0].module_aid.length; i++) {
        printf("%02X", dependent_module->imports[0].module_aid.aid[i]);
    }
    printf("\n");
    printf("  Required Version: %u.%u.%u.%u\n",
           (dependent_module->imports[0].module_version >> 24) & 0xFF,
           (dependent_module->imports[0].module_version >> 16) & 0xFF,
           (dependent_module->imports[0].module_version >> 8) & 0xFF,
           dependent_module->imports[0].module_version & 0xFF);
    
    /* Resolve dependency by AID matching */
    printf("\nResolving dependency by AID matching...\n");
    for (int i = 0; i < vm->module_count; i++) {
        if (vm->modules[i].module_aid.length == dependent_module->imports[0].module_aid.length &&
            memcmp(vm->modules[i].module_aid.aid, 
                   dependent_module->imports[0].module_aid.aid,
                   vm->modules[i].module_aid.length) == 0) {
            
            /* Check version compatibility */
            if (vm->modules[i].version >= dependent_module->imports[0].module_version) {
                dependent_module->imports[0].resolved = true;
                dependent_module->imports[0].resolved_module_id = vm->modules[i].module_id;
                
                printf("✓ Dependency resolved!\n");
                printf("  Found module ID: %u\n", vm->modules[i].module_id);
                printf("  Version match: %u.%u.%u.%u >= required %u.%u.%u.%u\n",
                       (vm->modules[i].version >> 24) & 0xFF,
                       (vm->modules[i].version >> 16) & 0xFF,
                       (vm->modules[i].version >> 8) & 0xFF,
                       vm->modules[i].version & 0xFF,
                       (dependent_module->imports[0].module_version >> 24) & 0xFF,
                       (dependent_module->imports[0].module_version >> 16) & 0xFF,
                       (dependent_module->imports[0].module_version >> 8) & 0xFF,
                       dependent_module->imports[0].module_version & 0xFF);
                break;
            }
        }
    }
    
    if (dependent_module->imports[0].resolved) {
        printf("\n✓ PASSED: AID-based dependency resolution works correctly\n");
        gcos_vm_destroy(vm);
        return 0;
    } else {
        printf("\n✗ FAILED: Could not resolve dependency\n");
        gcos_vm_destroy(vm);
        return 1;
    }
}

/**
 * @brief Main test entry point
 */
int main(void) {
    printf("========================================\n");
    printf("COS3 SEF File Parsing Test Suite\n");
    printf("========================================\n");
    
    int failures = 0;
    
    failures += test_cos3_sef_load();
    failures += test_dependency_by_aid();
    
    printf("\n========================================\n");
    if (failures == 0) {
        printf("All tests PASSED ✓\n");
    } else {
        printf("%d test(s) FAILED ✗\n", failures);
    }
    printf("========================================\n");
    
    printf("\nKey Findings:\n");
    printf("1. COS3 Appendix F.1 provides a complete SEF file example\n");
    printf("2. GCOS module dependencies are based on AID (not string names like WASM)\n");
    printf("3. Each import specifies:\n");
    printf("   - Required module AID (unique identifier)\n");
    printf("   - Required module version (for compatibility)\n");
    printf("   - Function index within the imported module\n");
    
    return failures;
}
